### ISSUE TITLE
Usage Example?

### ISSUE THREAD

**Issue by VD-NVencC** [Asd-g/AviSynthPlus-ssimulacra#1]
I'm not sure how to extract the statistics its likely computing, but not displaying

```
LoadPlugin("<dir>\ssimulacra.dll")
reference = ConvertToPlanarRGB(clip)
distortion = ConvertToPlanarRGB(clip2)
ssimulacra(reference,distortion,False,1)
-ssimulacra.avs
```

**Comment by Asd-g** [comment]
Add at the end of the script `propShow()`.

If you want to use the value you can get it by `propGetFloat("SSIMULACRA2")`  / `propGetFloat("SSIMULACRA")`.

**Comment by VD-NVencC** [comment]
Thank you, this appears to write the values correctly in AVSMeter 3.0.9.0, but have you encountered other applications writing the first value twice? ffmpeg, mpc-hc, virtualdub2 (pressing space after opening)
```
LoadPlugin("path\ssimulacra.dll")
reference = ConvertToPlanarRGB(Source("path\file1.ext"))
distortion = ConvertToPlanarRGB(Source("path\file2.ext"))
clip = ssimulacra(reference,distortion,False,1).propShow()

clip = FrameEvaluate(clip, """
    score = propGetFloat("SSIMULACRA2")
    WriteFileStart("path\example.csv","score",append=true)
""")

clip
-ssimulacra2.avs
```
[edit] I've since had success with changing the end of the script to..
```Prefetch(clip,1,2)```
..to avoid any double entries, this answer might be suboptimal from a non-programmer.
I may have been a little too hasty with praising AVSMeter, it was exporting the first 11 values, then the whole thing.

**Comment by Asd-g** [comment]
> but have you encountered other applications writing the first value twice? ffmpeg, mpc-hc, virtualdub2

Yes, this is a known behavior about the AVS functions for writing files. [Here](https://forum.doom9.org/showthread.php?p=1964538#post1964538) for example a solution for AvsPmod.

> I may have been a little too hasty with praising AVSMeter, it was exporting the first 11 values, then the whole thing.

For AVSMeter pass `-o` in this case (`AVSMeter your_script.avs -o`) to avoid the script prescanning. 

Also for such cases (run the script to create a file with some files) you can just use [avsr](https://forum.doom9.org/showthread.php?t=173259). This tool is meant exactly for this.

From `clip = ssimulacra(reference,distortion,False,1).propShow()` you can omit `.propShow()` if you will write a file. `.propShow()` can be used only if you want to see the score in the previewer.
