### ISSUE TITLE
Scoring issues

### ISSUE THREAD

**Issue by VD-NVencC** [Asd-g/AviSynthPlus-ssimulacra#2]
1) I opened/closed an issue at [[cloudinary/ssimulacra2]](https://github.com/cloudinary/ssimulacra2/issues/10), I wasn't seeing scores of 100 with bit-identical files while the author of ssimulacra did with their own implementation.

2) while using this plugin the propShow() and propGetFloat("SSIMULACRA2") written to file didn't agree by 0.000003~7(?) points in my observation (this one likely means very little)

[edit] I'll re-evaluate my observations after considering something I overlooked, which was leaving propShow() enabled during analysis runs

**Comment by Asd-g** [comment]
`ssimulacra(x, y, feature=0)` (ssimulacra) gives me `0.000x` for identical frames.

`ssimulacra(x, y, feature=1)` (ssimulacra2) (used [here](https://github.com/cloudinary/ssimulacra2/issues/10#issuecomment-1818859578)) gives me `>99.5` (depending on the resolution, smaller resolution -> closer to `100` for identical frames).

**Comment by VD-NVencC** [comment]
their ssimulacra2 was returning 100's on these
[edit]
and someone else was nice enough to supply their ssimulacra2_rs results
```
ssimulacra2_rs image 284050535-1e1e600b-c154-40ca-8f07-acb1b628af9d.png 284050535-1e1e600b-c154-40ca-8f07-acb1b628af9d.png
Score: 100.00000000
ssimulacra2_rs image 284050536-b464d209-8359-41da-9da5-b3679d2b1b9d.png 284050536-b464d209-8359-41da-9da5-b3679d2b1b9d.png
Score: 100.00000000
ssimulacra2_rs image 284050537-441e867b-3a3c-4ff0-9cb0-7ca757a6b30c.png 284050537-441e867b-3a3c-4ff0-9cb0-7ca757a6b30c.png
Score: 100.00000000
```

![00001](https://github.com/Asd-g/AviSynthPlus-ssimulacra/assets/71042674/eddfa2a7-144f-4f2c-aa12-1465e3c511ef)
![00003](https://github.com/Asd-g/AviSynthPlus-ssimulacra/assets/71042674/bca41e5c-5226-48e7-9242-d72fa6e379f6)
![00005](https://github.com/Asd-g/AviSynthPlus-ssimulacra/assets/71042674/5d2673b2-b431-470e-8ac9-60300e9fdd6b)

I've seen a range of 99.1~99.7 depending on the subject of the material so far. I've observed omitting `.propShow()` and keeping it on during the analysis gave (601/601) identical scores for the same content.

**Comment by Asd-g** [comment]
The compiler I used is optimizing the score. That's the reason to see not exactly 100. Try the attached version.

[ssimulacra.zip](https://github.com/Asd-g/AviSynthPlus-ssimulacra/files/13423071/ssimulacra.zip)

**Comment by VD-NVencC** [comment]
> Try the attached version.

I do see 100's with identical files now. The speed of the operation was impacted (1.8 vs the 2.4 fps on (601 frames) 2560x1440 material, on my system) but as long as it'll mirror others results I don't mind, thank you.

[edit]
confirmed 1.1.0.1 has nearly the same performance as before, 2.3 fps on my system

**Comment by Asd-g** [comment]
[1.1.0.1](https://github.com/Asd-g/AviSynthPlus-ssimulacra/releases/tag/1.1.0.1) should give better fps than the test version in my previous post.
